factors.html: factors.md
	pandoc -s factors.md -o factors.html

permissions.html: permissions.md
	pandoc -s permissions.md -o permissions.html

unexpected.html: unexpected.md
	pandoc -s unexpected.md -o unexpected.html

clean:
	rm -f factors.html permissions.html unexpected.html
